# Generated by Django 3.2.5 on 2023-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Id', models.IntegerField()),
                ('c_phone_number', models.CharField(max_length=20)),
                ('v_id', models.IntegerField()),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
