# Generated by Django 3.2.5 on 2023-05-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_remove_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
