# Generated by Django 3.2.5 on 2023-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('time_of_pickup', models.DateTimeField()),
            ],
        ),
    ]
